name: baty_bites
description: "Baty Food is a vibrant dual-app platform connecting customers craving authentic homemade meals with talented home chefs, designed to bring the taste of home directly to your pocket."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.0.0
  flutter_riverpod: ^2.5.1
  go_router: ^16.0.0
  dio: ^5.0.0
  shared_preferences: ^2.0.0
  cached_network_image: ^3.0.0
  image_picker: ^1.0.7
  connectivity_plus: ^5.0.2
  firebase_messaging: ^14.7.10
  firebase_core: ^2.24.2
  flutter_local_notifications: ^16.3.2
  flutter_cache_manager: ^3.3.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
