name: baty_bites
description: "Baty Food is a vibrant dual-app platform connecting customers craving authentic homemade meals with talented home chefs, designed to bring the taste of home directly to your pocket."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.0.0
  go_router: ^16.0.0
  dio: ^5.0.0
  shared_preferences: ^2.0.0
  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
