import 'package:baty_bites/models/recipe.dart';
import 'package:baty_bites/models/user.dart';
import 'package:baty_bites/models/address.dart';
import 'package:baty_bites/models/order.dart';
import 'package:baty_bites/core/constants/app_constants.dart';

class SampleDataService {
  static List<Recipe> getSampleRecipes() {
    return [
      Recipe(
        id: '1',
        chefId: 'chef1',
        chefName: 'فاطمة أحمد',
        chefImage: AppConstants.sampleChefImages[0],
        title: 'كشري بيتي',
        description: 'كشري مصري أصيل بالطريقة التقليدية مع الأرز والعدس والمكرونة والصلصة الحارة',
        ingredients: [
          const Ingredient(name: 'أرز أبيض', quantity: '2', unit: 'كوب'),
          const Ingredient(name: 'عدس أسود', quantity: '1', unit: 'كوب'),
          const Ingredient(name: 'مكرونة', quantity: '200', unit: 'جرام'),
          const Ingredient(name: 'بصل', quantity: '3', unit: 'حبات'),
          const Ingredient(name: 'طماطم', quantity: '4', unit: 'حبات'),
          const Ingredient(name: 'ثوم', quantity: '4', unit: 'فصوص'),
          const Ingredient(name: 'حمص', quantity: '1', unit: 'كوب'),
        ],
        instructions: [
          const CookingStep(stepNumber: 1, instruction: 'اسلقي الأرز والعدس والحمص كل منهما على حدة', timeMinutes: 30),
          const CookingStep(stepNumber: 2, instruction: 'اسلقي المكرونة حتى تنضج', timeMinutes: 15),
          const CookingStep(stepNumber: 3, instruction: 'قطعي البصل شرائح واقليه حتى يذبل ويصبح ذهبي اللون', timeMinutes: 10),
          const CookingStep(stepNumber: 4, instruction: 'حضري الصلصة بخلط الطماطم والثوم والتوابل', timeMinutes: 20),
          const CookingStep(stepNumber: 5, instruction: 'اخلطي جميع المكونات واتركيها تنضج معاً', timeMinutes: 10),
        ],
        price: 35.0,
        images: [AppConstants.sampleRecipeImages[0]],
        cuisineType: 'مصري',
        category: 'أطباق رئيسية',
        preparationTime: 20,
        cookingTime: 65,
        servings: 4,
        difficulty: DifficultyLevel.medium,
        spiceLevel: SpiceLevel.medium,
        dietaryInfo: const DietaryInfo(isVegetarian: true, isHalal: true),
        tags: ['كشري', 'مصري', 'نباتي', 'شعبي'],
        isFeatured: true,
        rating: 4.8,
        totalReviews: 127,
        orderCount: 89,
        createdAt: DateTime.now().subtract(const Duration(days: 30)),
        updatedAt: DateTime.now().subtract(const Duration(days: 1)),
        reviews: [],
      ),
      Recipe(
        id: '2',
        chefId: 'chef2',
        chefName: 'أم محمد',
        chefImage: AppConstants.sampleChefImages[1],
        title: 'ملوخية بالفراخ',
        description: 'ملوخية خضراء طازجة مع الفراخ البلدي والأرز الأبيض',
        ingredients: [
          const Ingredient(name: 'ملوخية خضراء', quantity: '500', unit: 'جرام'),
          const Ingredient(name: 'فراخ بلدي', quantity: '1', unit: 'كيلو'),
          const Ingredient(name: 'أرز أبيض', quantity: '2', unit: 'كوب'),
          const Ingredient(name: 'شوربة فراخ', quantity: '4', unit: 'أكواب'),
          const Ingredient(name: 'ثوم', quantity: '6', unit: 'فصوص'),
          const Ingredient(name: 'كزبرة ناشفة', quantity: '2', unit: 'ملعقة صغيرة'),
        ],
        instructions: [
          const CookingStep(stepNumber: 1, instruction: 'اسلقي الفراخ مع البصل والتوابل', timeMinutes: 45),
          const CookingStep(stepNumber: 2, instruction: 'قطعي الملوخية ناعم جداً', timeMinutes: 15),
          const CookingStep(stepNumber: 3, instruction: 'حمري الثوم في الزيت مع الكزبرة', timeMinutes: 5),
          const CookingStep(stepNumber: 4, instruction: 'أضيفي الملوخية للشوربة واتركيها تنضج', timeMinutes: 20),
        ],
        price: 65.0,
        images: [AppConstants.sampleRecipeImages[1]],
        cuisineType: 'مصري',
        category: 'أطباق رئيسية',
        preparationTime: 25,
        cookingTime: 60,
        servings: 6,
        difficulty: DifficultyLevel.medium,
        spiceLevel: SpiceLevel.mild,
        dietaryInfo: const DietaryInfo(isHalal: true),
        tags: ['ملوخية', 'فراخ', 'مصري', 'شوربة'],
        rating: 4.9,
        totalReviews: 203,
        orderCount: 156,
        createdAt: DateTime.now().subtract(const Duration(days: 15)),
        updatedAt: DateTime.now().subtract(const Duration(hours: 6)),
        reviews: [],
      ),
      Recipe(
        id: '3',
        chefId: 'chef1',
        chefName: 'فاطمة أحمد',
        chefImage: AppConstants.sampleChefImages[0],
        title: 'كنافة بالقشطة',
        description: 'كنافة طازجة محشوة بالقشطة الطبيعية ومحلاة بالعسل الأبيض',
        ingredients: [
          const Ingredient(name: 'عجينة كنافة', quantity: '500', unit: 'جرام'),
          const Ingredient(name: 'قشطة طبيعية', quantity: '300', unit: 'جرام'),
          const Ingredient(name: 'سكر', quantity: '200', unit: 'جرام'),
          const Ingredient(name: 'ماء', quantity: '1', unit: 'كوب'),
          const Ingredient(name: 'عسل أبيض', quantity: '3', unit: 'ملاعق كبيرة'),
          const Ingredient(name: 'فستق مفروم', quantity: '50', unit: 'جرام'),
        ],
        instructions: [
          const CookingStep(stepNumber: 1, instruction: 'حضري الشربات بغلي السكر والماء', timeMinutes: 10),
          const CookingStep(stepNumber: 2, instruction: 'افردي نصف الكنافة في الصينية المدهونة', timeMinutes: 5),
          const CookingStep(stepNumber: 3, instruction: 'ضعي القشطة فوق الكنافة وغطيها بالباقي', timeMinutes: 5),
          const CookingStep(stepNumber: 4, instruction: 'اخبزي في الفرن حتى تصبح ذهبية', timeMinutes: 25),
          const CookingStep(stepNumber: 5, instruction: 'اسكبي الشربات البارد فوق الكنافة الساخنة', timeMinutes: 2),
        ],
        price: 45.0,
        images: [AppConstants.sampleRecipeImages[2]],
        cuisineType: 'مصري',
        category: 'حلويات',
        preparationTime: 20,
        cookingTime: 30,
        servings: 8,
        difficulty: DifficultyLevel.medium,
        spiceLevel: SpiceLevel.mild,
        dietaryInfo: const DietaryInfo(isVegetarian: true, isHalal: true),
        tags: ['كنافة', 'قشطة', 'حلويات', 'مصري'],
        rating: 4.7,
        totalReviews: 89,
        orderCount: 67,
        createdAt: DateTime.now().subtract(const Duration(days: 7)),
        updatedAt: DateTime.now().subtract(const Duration(hours: 2)),
        reviews: [],
      ),
      Recipe(
        id: '4',
        chefId: 'chef2',
        chefName: 'أم محمد',
        title: 'ورق عنب بالحنة',
        description: 'ورق عنب محشو باللحمة المفرومة والأرز وورق العنب الطري',
        ingredients: [
          const Ingredient(name: 'ورق عنب', quantity: '200', unit: 'ورقة'),
          const Ingredient(name: 'لحمة مفرومة', quantity: '300', unit: 'جرام'),
          const Ingredient(name: 'أرز أبيض', quantity: '1', unit: 'كوب'),
          const Ingredient(name: 'بقدونس مفروم', quantity: '1/2', unit: 'كوب'),
          const Ingredient(name: 'طماطم مقطعة', quantity: '2', unit: 'حبات'),
          const Ingredient(name: 'بصل مفروم', quantity: '1', unit: 'حبة'),
        ],
        instructions: [
          const CookingStep(stepNumber: 1, instruction: 'انقعي ورق العنب في الماء المالح', timeMinutes: 30),
          const CookingStep(stepNumber: 2, instruction: 'حضري الحشو بخلط اللحمة والأرز والتوابل', timeMinutes: 15),
          const CookingStep(stepNumber: 3, instruction: 'احشي أوراق العنب ولفيها بإحكام', timeMinutes: 45),
          const CookingStep(stepNumber: 4, instruction: 'رصيها في الحلة واتركيها تنضج', timeMinutes: 60),
        ],
        price: 55.0,
        images: [AppConstants.sampleRecipeImages[3]],
        cuisineType: 'شامي',
        category: 'أطباق رئيسية',
        preparationTime: 60,
        cookingTime: 75,
        servings: 6,
        difficulty: DifficultyLevel.hard,
        spiceLevel: SpiceLevel.mild,
        dietaryInfo: const DietaryInfo(isHalal: true),
        tags: ['ورق عنب', 'لحمة', 'شامي', 'محشي'],
        rating: 4.6,
        totalReviews: 156,
        orderCount: 134,
        createdAt: DateTime.now().subtract(const Duration(days: 20)),
        updatedAt: DateTime.now().subtract(const Duration(days: 3)),
        reviews: [],
      ),
      Recipe(
        id: '5',
        chefId: 'chef1',
        chefName: 'فاطمة أحمد',
        title: 'فتة الدجاج',
        description: 'فتة لذيذة بالدجاج المسلوق والأرز الأبيض وصلصة الطحينة والثوم',
        ingredients: [
          const Ingredient(name: 'دجاج مسلوق', quantity: '500', unit: 'جرام'),
          const Ingredient(name: 'أرز أبيض', quantity: '2', unit: 'كوب'),
          const Ingredient(name: 'خبز محمص', quantity: '4', unit: 'أرغفة'),
          const Ingredient(name: 'طحينة', quantity: '4', unit: 'ملاعق كبيرة'),
          const Ingredient(name: 'لبن زبادي', quantity: '1', unit: 'كوب'),
          const Ingredient(name: 'ثوم مفروم', quantity: '4', unit: 'فصوص'),
        ],
        instructions: [
          const CookingStep(stepNumber: 1, instruction: 'اسلقي الدجاج مع التوابل واحتفظي بالشوربة', timeMinutes: 45),
          const CookingStep(stepNumber: 2, instruction: 'اطبخي الأرز في شوربة الفراخ', timeMinutes: 20),
          const CookingStep(stepNumber: 3, instruction: 'حضري صلصة الطحينة بخلطها مع اللبن والثوم', timeMinutes: 10),
          const CookingStep(stepNumber: 4, instruction: 'رصي الخبز المحمص والأرز والدجاج', timeMinutes: 10),
          const CookingStep(stepNumber: 5, instruction: 'اسكبي الصلصة وقدميها ساخنة', timeMinutes: 5),
        ],
        price: 48.0,
        images: [AppConstants.sampleRecipeImages[4]],
        cuisineType: 'مصري',
        category: 'أطباق رئيسية',
        preparationTime: 25,
        cookingTime: 70,
        servings: 4,
        difficulty: DifficultyLevel.medium,
        spiceLevel: SpiceLevel.mild,
        dietaryInfo: const DietaryInfo(isHalal: true),
        tags: ['فتة', 'دجاج', 'طحينة', 'مصري'],
        rating: 4.5,
        totalReviews: 78,
        orderCount: 45,
        createdAt: DateTime.now().subtract(const Duration(days: 12)),
        updatedAt: DateTime.now().subtract(const Duration(hours: 8)),
        reviews: [],
      ),
      Recipe(
        id: '6',
        chefId: 'chef2',
        chefName: 'أم محمد',
        title: 'بسبوسة بالقشطة',
        description: 'بسبوسة طرية بالقشطة الطبيعية والعسل الأبيض مع جوز الهند',
        ingredients: [
          const Ingredient(name: 'سميد ناعم', quantity: '2', unit: 'كوب'),
          const Ingredient(name: 'جوز هند مبشور', quantity: '1/2', unit: 'كوب'),
          const Ingredient(name: 'قشطة طبيعية', quantity: '200', unit: 'جرام'),
          const Ingredient(name: 'لبن', quantity: '1', unit: 'كوب'),
          const Ingredient(name: 'سكر', quantity: '1', unit: 'كوب'),
          const Ingredient(name: 'بيكينج بودر', quantity: '2', unit: 'ملعقة صغيرة'),
        ],
        instructions: [
          const CookingStep(stepNumber: 1, instruction: 'اخلطي السميد وجوز الهند والبيكينج بودر', timeMinutes: 5),
          const CookingStep(stepNumber: 2, instruction: 'أضيفي اللبن والقشطة واخلطي جيداً', timeMinutes: 10),
          const CookingStep(stepNumber: 3, instruction: 'اتركي الخليط ينتفش لمدة 30 دقيقة', timeMinutes: 30),
          const CookingStep(stepNumber: 4, instruction: 'اسكبي في الصينية المدهونة واخبزي', timeMinutes: 35),
        ],
        price: 40.0,
        images: [AppConstants.sampleRecipeImages[5]],
        cuisineType: 'مصري',
        category: 'حلويات',
        preparationTime: 15,
        cookingTime: 65,
        servings: 12,
        difficulty: DifficultyLevel.easy,
        spiceLevel: SpiceLevel.mild,
        dietaryInfo: const DietaryInfo(isVegetarian: true, isHalal: true),
        tags: ['بسبوسة', 'قشطة', 'جوز هند', 'حلويات'],
        rating: 4.4,
        totalReviews: 92,
        orderCount: 58,
        createdAt: DateTime.now().subtract(const Duration(days: 5)),
        updatedAt: DateTime.now().subtract(const Duration(hours: 4)),
        reviews: [],
      ),
    ];
  }

  static List<User> getSampleChefs() {
    return [
      User(
        id: 'chef1',
        fullName: 'فاطمة أحمد',
        email: 'fatma@example.com',
        phone: '+201234567890',
        profileImage: AppConstants.sampleChefImages[0],
        userType: UserType.chef,
        createdAt: DateTime.now().subtract(const Duration(days: 180)),
        isVerified: true,
        rating: 4.8,
        totalReviews: 294,
        address: Address(
          id: 'addr1',
          street: 'شارع النصر',
          area: 'الحي الخامس',
          city: 'القاهرة الجديدة',
          latitude: 30.0444,
          longitude: 31.2357,
        ),
      ),
      User(
        id: 'chef2',
        fullName: 'أم محمد',
        email: 'ummohammad@example.com',
        phone: '+201987654321',
        profileImage: AppConstants.sampleChefImages[1],
        userType: UserType.chef,
        createdAt: DateTime.now().subtract(const Duration(days: 90)),
        isVerified: true,
        rating: 4.9,
        totalReviews: 458,
        address: Address(
          id: 'addr2',
          street: 'شارع ٩٠',
          area: 'التجمع الخامس',
          city: 'القاهرة الجديدة',
          latitude: 30.0626,
          longitude: 31.4285,
        ),
      ),
    ];
  }

  static List<Order> getSampleOrders({required String userId, required UserType userType}) {
    final recipes = getSampleRecipes();
    final chefs = getSampleChefs();
    
    return [
      Order(
        id: 'order1',
        customerId: userType == UserType.customer ? userId : 'customer1',
        customerName: userType == UserType.customer ? 'أحمد محمد' : 'أحمد محمد',
        customerImage: '',
        chefId: userType == UserType.chef ? userId : recipes[0].chefId,
        chefName: recipes[0].chefName,
        chefImage: recipes[0].chefImage,
        recipeId: recipes[0].id,
        recipeTitle: recipes[0].title,
        recipeImage: recipes[0].images.first,
        quantity: 2,
        unitPrice: recipes[0].price,
        deliveryFee: 10.0,
        totalPrice: (recipes[0].price * 2) + 10.0,
        status: OrderStatus.preparing,
        deliveryAddress: Address(
          id: 'addr3',
          street: 'شارع الجامعة',
          area: 'مدينة نصر',
          city: 'القاهرة',
          building: '12',
          floor: '3',
          apartment: '5',
          latitude: 30.0626,
          longitude: 31.3219,
        ),
        deliveryInstructions: 'الرجاء الاتصال عند الوصول',
        paymentMethod: PaymentMethod.cash,
        paymentStatus: PaymentStatus.pending,
        estimatedDeliveryTime: DateTime.now().add(const Duration(minutes: 45)),
        createdAt: DateTime.now().subtract(const Duration(hours: 2)),
        updatedAt: DateTime.now().subtract(const Duration(minutes: 30)),
      ),
      Order(
        id: 'order2',
        customerId: userType == UserType.customer ? userId : 'customer2',
        customerName: userType == UserType.customer ? 'سارة علي' : 'سارة علي',
        customerImage: '',
        chefId: userType == UserType.chef ? userId : recipes[1].chefId,
        chefName: recipes[1].chefName,
        chefImage: recipes[1].chefImage,
        recipeId: recipes[1].id,
        recipeTitle: recipes[1].title,
        recipeImage: recipes[1].images.first,
        quantity: 1,
        unitPrice: recipes[1].price,
        deliveryFee: 0.0, // Free delivery
        totalPrice: recipes[1].price,
        status: OrderStatus.delivered,
        deliveryAddress: Address(
          id: 'addr4',
          street: 'شارع التسعين',
          area: 'التجمع الخامس',
          city: 'القاهرة الجديدة',
          latitude: 30.0626,
          longitude: 31.4285,
        ),
        paymentMethod: PaymentMethod.cash,
        paymentStatus: PaymentStatus.paid,
        actualDeliveryTime: DateTime.now().subtract(const Duration(days: 2, hours: 3)),
        createdAt: DateTime.now().subtract(const Duration(days: 3)),
        updatedAt: DateTime.now().subtract(const Duration(days: 2, hours: 3)),
      ),
    ];
  }
}