/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lmyxrrscocsvgiqyarqu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxteXhycnNjb2NzdmdpcXlhcnF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMzgwMzIsImV4cCI6MjA2OTcxNDAzMn0.yRbXMvbfsF-R8qwdQGco-sEJu7GGDJ63kaY_ZDhZdRI"